= Developer Information

== Install dependencies

This application requires at least Node.js 6.9.0 and NPM 3. Run `npm install` to get all dependencies.

== Development Stack

Requirements to run the Stack:

- https://docker.com/[docker] with docker-compose
- Linux or macOS

To start the test stack, run:
```bash
export UID
docker-compose up
```

The development stack consists of three components: A openfire XMPP server, node as an application server, and a nginx server to proxy both.

Following services are provided:

|===
|Service |URL |Authentication

|XMPP-Grid Broker with auto-reload on changes |https://xgb.localhost.redbackup.org/ |TLS client certificate (see below)
|Openfire BOSH |https://xgb.localhost.redbackup.org/http-bind/ |TLS client certificate (see below)
|Openfire WebSocket |https://xgb.localhost.redbackup.org/ws/ |TLS client certificate (see below)
|Openfire administration interface |https://openfire-admin.localhost.redbackup.org/ |Username: `admin`, Password: `1q2w3e4r`
|===

`*.localhost.redbackup.org` is an alias for `127.0.0.1`; if you want to work offline, simply add that to your `/etc/hosts` file.

=== TLS Certificates and Test Users

All TLS server and client certificates as well as the according test-CA are provided in `stack/certs/`.

To authenticate to the XMPP-Grid Broker, you can add the according client-certificate to your browser beforehand.

In Firefox, you can add them in the Preferences under `Privacy & Security` -> `View-Certificates` -> `Your Certificates`.

Importing the CA is **not recommended** because it's private key is publicly accessible!
In Firefox, add a permanent exception when accessing `https://xgb.localhost.redbackup.org/` for the first time.

|===
|JID |User Password |Certificate | P12-Password

|eva@openfire |123456 |`stack/certs/keys/client/eva@openfire/eva@openfire.p12`| _no password_
|admin |1q2w3e4r | `stack/certs/keys/client/eva@openfire/eva@openfire.p12`|_no password_
|===

The `admin` certificate is used by nginx to authenticate itself to the xmpp server (openfire).

=== Generate New Certificates

If you want to generate a new CA and certificates, execute the following steps:

[source, bash]
----
# Requires openssl binary and bash.
pushd stack/certs/
  rm -r keys/
  ./generate.bash
popd

# Add CA to openfire (requires docker)
pushd stack/
  ./add_certs_to_openfire.bash
popd
----

You might also want to add the CA from `stack/certs/keys/ca-fullchain.pem` and client certificates from `stack/certs/keys/client/` to your webbrowser as described in section <<TLS Certificates and Test Users>>.

=== Edit Openfire Configuration

To edit the Openfire Configuration (e.g. for adding new users or TLS certificates), you have to execute following steps:

[source, bash]
----
export UID
docker-compose -f docker-compose.openfire-admin.yml -f docker-compose.yml up <1>

sudo chown -R $UID stack/openfire <1>

docker-compose build <2>
----
<1> You can now configure Openfire over the https://openfire-admin.localhost.redbackup.org[Web Interface]. If done, press `Ctrl + C` to stop openfire.
<2> Clean up access permissions after finishing
<3> Recreate image (note that you reset/lose the current openfire content with this!)


== Builds and Tests

=== Code scaffolding

Run `npm run ng generate component component-name` to generate a new component. You can also use `npm run ng generate directive|pipe|service|class|guard|interface|enum|module`.

=== Build

Run `npm run ng build` to build the project. The build artifacts will be stored in the `dist/` directory. Use the `-prod` flag for a production build.

=== Running unit tests

Run `npm run ng test` to execute the unit tests via https://karma-runner.github.io[Karma].

=== Running end-to-end tests

Run `npm run ng e2e` to execute the end-to-end tests via http://www.protractortest.org/[Protractor].

=== Further help

To get more help on the Angular CLI use `npm run ng help` or go check out the https://github.com/angular/angular-cli/blob/master/README.md[Angular CLI README].
