sudo: required
services:
  - docker
cache:
  directories:
    - .cache
script:
  - ./build_archive.bash
deploy:
  provider: pages
  local-dir: export/
  skip-cleanup: true
  repo: xmpp-grid-broker/xmpp-grid-broker.github.io
  project-name: xmpp-grid-broker.github.io
  github-token: $GITHUB_TOKEN
  target-branch: master
  keep-history: true
  on:
    branch: master
