= XMPP-Grid Broker
https://travis-ci.org/xmpp-grid-broker/xmpp-grid-broker[image::https://travis-ci.org/xmpp-grid-broker/xmpp-grid-broker.svg?branch=master[Build Status]]

The XMPP-Grid Broker is a client web application to simplify the management of an https://tools.ietf.org/id/draft-ietf-mile-xmpp-grid-05.html[XMPP-Grid].

== Documentation

- link:docs/TUTORIAL.adoc[Tutorial With Openfire and Nginx]
- link:docs/INSTALL.adoc[Expert Installation Guide]
- link:docs/DEVELOPMENT.adoc[Development Information]
- link:docs/SECURITY.adoc[Security Reference]

== Thesis

This project was created as part of the bachelor thesis by Fabian Hauser and Raphael Zimmermann, see https://xmpp-grid-broker.github.io/[xmpp-grid-broker.github.io].

== License

Copyright © 2018 Raphael Zimmermann and Fabian Hauser

> This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
>
> This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.
>
> You should have received a copy of the GNU Affero General Public License along with this program.  If not, see <https://www.gnu.org/licenses/>.
